### ISSUE TITLE
Runtime theme update for Windows

### ISSUE THREAD

**Issue by martpie** [wyhaya/tauri-plugin-theme#5]
Right now, the app restarts when updating the theme on Windows. [Electron's `nativeTheme`](https://www.electronjs.org/docs/latest/api/native-theme#nativethemethemesource) seems to work without restarting the app. 

I wonder if there's some inspiration to get from there?

https://github.com/electron/electron/blob/02020fbb6387bd072ede38634a3b6f3f3f225526/shell/browser/api/electron_api_native_theme.cc

**Comment by ayangweb** [comment]
@wyhaya https://github.com/tauri-apps/tao/pull/937

Hey 👋, excuse me, this pr might bring some inspiration?

**Comment by wyhaya** [comment]
> Hey👋, excuse me, this pr might bring some inspiration?

I'm not sure if it can be properly propagated to the webview; I've tried many times.

---

I just found a new function from wry to set the theme directly on the webview, which means no more restart on Windows.
[webview.set_theme](https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/struct.WebView.html#method.set_theme)

However, it seems that it is not publicly available in Tauri, and I cannot access it from Tauri's PlatformWebview.

**Comment by wyhaya** [comment]
Try it: #17

It works well on my Windows 11, but I'm not sure if there are any compatibility issues.

https://github.com/user-attachments/assets/0f679fe6-320a-44a3-a91e-273dddff7e28

**Comment by ayangweb** [comment]
> Try it: #17
> 
> It works well on my Windows 11, but I'm not sure if there are any compatibility issues.
> 
>  windows.mp4

Really great, but tauri v2 has not yet come out of the official version, currently using or v1, do not know v1 implementation is not the same!

**Comment by martpie** [comment]
I believe though tauri v2 is still in release candidate, most of the community including third party plugins moved to v2 for their master branches.

I would highly encourage you to start looking at the migration path to v2 as the whole community embraced it, and it's been stable for quite some time.

**Comment by wyhaya** [comment]
> Really great, but tauri v2 has not yet come out of the official version, currently using or v1, do not know v1 implementation is not the same!

I tried to do the same thing on v1, but it failed because the version of `webview2-com-sys` used in Tauri v1 is too old.
I share the same opinion as @martpie and suggest migrating to Tauri v2.

The version for Tauri v2 (v2.1.1) has been released, which will change both the window theme and the webview theme. please see the [NOTE](https://github.com/wyhaya/tauri-plugin-theme?tab=readme-ov-file#note).

**Comment by ayangweb** [comment]
> > Really great, but tauri v2 has not yet come out of the official version, currently using or v1, do not know v1 implementation is not the same!
> 
> I tried to do the same thing on v1, but it failed because the version of `webview2-com-sys` used in Tauri v1 is too old. I share the same opinion as @martpie and suggest migrating to Tauri v2.
> 
> The version for Tauri v2 (v2.1.1) has been released, which will change both the window theme and the webview theme. please see the [NOTE](https://github.com/wyhaya/tauri-plugin-theme?tab=readme-ov-file#note).

I understand the reasoning, but it would still be challenging to migrate my existing project to tauri v2 🥹!
